version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_API_USERNAME: ${NEXT_PUBLIC_API_USERNAME}
        NEXT_PUBLIC_API_PASSWORD: ${NEXT_PUBLIC_API_PASSWORD}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
